apiVersion: v1
kind: Service
metadata:
  name: app1-service
  namespace: app1
spec:
  selector:
    app: app1-deployment
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
      name: http
  type: LoadBalancer
  #LoadBalancer